opt_out_usage
default_platform(:ios)

DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  lane :prepare_xcode_project do
    system("git clone --recursive https://github.com/MeridianOXC/openxcom-ios ../openxcom-ios")
    # lock version
    system("sh -c \"git --git-dir ../openxcom-ios/.git checkout f1e667bd04da512601e90189422f5c2411eeb86f\"")

    system("sh -c \"cp -r ../Assets.xcassets ../openxcom-ios/Sources/OpenXcom/xcode-ios/\"")
    system("sh -c \"cp -r ../schemes/xcshareddata ../openxcom-ios/Sources/OpenXcom/xcode-ios/OpenXcom.xcodeproj/\"")
    system("sh -c \"cp -r ../schemes/project.xcworkspace ../openxcom-ios/Sources/OpenXcom/xcode-ios/OpenXcom.xcodeproj/\"")
    system("sh -c \"cp ../schemes/Info.plist ../openxcom-ios/Sources/OpenXcom/xcode-ios/\"")
    system("sh -c \"cp ../schemes/OpenXcom-Info.plist ../openxcom-ios/Sources/OpenXcom/xcode-ios/\"")
    system("sh -c \"cp ../schemes/project.pbxproj ../openxcom-ios/Sources/OpenXcom/xcode-ios/OpenXcom.xcodeproj/\"")
  end

  lane :cleanup do
    system("sh -c \"rm -rf ../openxcom-ios\"")
    system("sh -c \"rm -rf ../Game.app.dSYM.zip\"")
    system("sh -c \"rm -rf ../Game.ipa\"")
  end

  lane :closed_beta do
    prepare_xcode_project

    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)

    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,
      duration: 1200,
      in_house: false
    )

    increment_build_number(xcodeproj: "./openxcom-ios/Sources/OpenXcom/xcode-ios/OpenXcom.xcodeproj")

    match(
      type: 'appstore',
      app_identifier: ["#{DEVELOPER_APP_IDENTIFIER}"],
      git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      api_key: api_key
    )

    gym(
      configuration: "Release",
      workspace: "./openxcom-ios/Sources/OpenXcom/xcode-ios/OpenXcom.xcodeproj/project.xcworkspace",
      scheme: "Game",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
            DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER
        }
      }
    )

    pilot(
      apple_id: "#{DEVELOPER_APP_ID}",
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      skip_waiting_for_build_processing: false,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "Game.ipa"
    )

    delete_temp_keychain(keychain_name)

    # update project.pbxproj in the repo
    system("sh -c \"cp ../openxcom-ios/Sources/OpenXcom/xcode-ios/OpenXcom.xcodeproj/project.pbxproj ../schemes/project.pbxproj\"")

    cleanup
  end
end
